debugging

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -70,123 +70,128 @@ jobs:
             python -m doc8 --ignore D001 HISTORY.rst README_PYTHON.rst
 
 
-  run-ubuntu-model-tests:
-    name: Run model tests (ubuntu)
-    runs-on: ubuntu-latest
-    needs: check-syntax-errors
-    container:
-      image: quay.io/pypa/manylinux_2_28_x86_64
-      env:
-        PLAT: manylinux_2_28_x86_64
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [3.9, "3.10", "3.11", "3.12", "3.13"]
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Fetch complete history for accurate versioning
+  # run-ubuntu-model-tests:
+  #   name: Run model tests (ubuntu)
+  #   runs-on: ubuntu-latest
+  #   needs: check-syntax-errors
+  #   container:
+  #     image:
+  #     env:
+  #       PLAT: manylinux_2_28_x86_64
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.9, "3.10", "3.11", "3.12", "3.13"]
 
-      # NOTE: It takes twice as long to save the sample data cache
-      # as it does to do a fresh clone (almost 5 minutes vs. 2.5 minutes)
-      # Test data is way, way faster by contrast (on the order of a few
-      # seconds to archive).
-      - name: Restore git-LFS test data cache
-        uses: actions/cache@v3
-        with:
-          path: data/invest-test-data
-          key: git-lfs-testdata-${{ hashfiles('Makefile') }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # Fetch complete history for accurate versioning
 
-      - name: Set up python environment
-        uses: ./.github/actions/setup_env
-        with:
-          setup-python: false
-          python: /opt/python/cp39-cp39/bin/python
-          python-version: ${{ matrix.python-version }}
-          requirements-files: requirements.txt requirements-dev.txt constraints_tests.txt
-          requirements: ${{ env.CONDA_DEFAULT_DEPENDENCIES }} sqlite<3.49.1  # https://github.com/natcap/invest/issues/1797
+  #     # NOTE: It takes twice as long to save the sample data cache
+  #     # as it does to do a fresh clone (almost 5 minutes vs. 2.5 minutes)
+  #     # Test data is way, way faster by contrast (on the order of a few
+  #     # seconds to archive).
+  #     - name: Restore git-LFS test data cache
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: data/invest-test-data
+  #         key: git-lfs-testdata-${{ hashfiles('Makefile') }}
 
-      - name: Download previous conda environment.yml
-        continue-on-error: true
-        # Using 'dawidd6' since 'download-artifact' GH action doesn't
-        # support downloading artifacts from prior workflow runs
-        uses: dawidd6/action-download-artifact@v2
-        with:
-          workflow: build-and-test.yml
-          # Get frozen conda env artifact from last successful workflow
-          workflow_conclusion: success
-          name: Conda Env for ${{ matrix.os }} ${{ matrix.python-version }}
-          path: ./conda-env-artifact
+  #     - name: Set up python environment
+  #       uses: ./.github/actions/setup_env
+  #       with:
+  #         setup-python: false
+  #         python: /opt/python/cp39-cp39/bin/python
+  #         python-version: ${{ matrix.python-version }}
+  #         requirements-files: requirements.txt requirements-dev.txt constraints_tests.txt
+  #         requirements: ${{ env.CONDA_DEFAULT_DEPENDENCIES }} sqlite<3.49.1  # https://github.com/natcap/invest/issues/1797
 
-      - name: Compare conda environments
-        run: |
-          micromamba list > conda-env.txt
-          # make sure that the exit code is always 0
-          # otherwise, an error appears in the action annotations
-          diff ./conda-env.txt ./conda-env-artifact/conda-env.txt || true
+  #     - name: Download previous conda environment.yml
+  #       continue-on-error: true
+  #       # Using 'dawidd6' since 'download-artifact' GH action doesn't
+  #       # support downloading artifacts from prior workflow runs
+  #       uses: dawidd6/action-download-artifact@v2
+  #       with:
+  #         workflow: build-and-test.yml
+  #         # Get frozen conda env artifact from last successful workflow
+  #         workflow_conclusion: success
+  #         name: Conda Env for ${{ matrix.os }} ${{ matrix.python-version }}
+  #         path: ./conda-env-artifact
 
-      - name: Build and install wheel
-        env:
-          PIP_ROOT_USER_ACTION: ignore
-        run: |
-          chown -R $(whoami) /github/home
-          git config --global --add safe.directory /__w/invest/invest
+  #     - name: Compare conda environments
+  #       run: |
+  #         micromamba list > conda-env.txt
+  #         # make sure that the exit code is always 0
+  #         # otherwise, an error appears in the action annotations
+  #         diff ./conda-env.txt ./conda-env-artifact/conda-env.txt || true
 
-          # uninstall InVEST if it was already in the restored cache
-          python -m pip uninstall -y natcap.invest
-          python -m build --wheel
-          ls -la dist
-          python -m pip install $(find dist -name "natcap.invest*.whl")
-          python -m pip list
+  #     - name: Build and install wheel
+  #       env:
+  #         PIP_ROOT_USER_ACTION: ignore
+  #       run: |
+  #         chown -R $(whoami) /github/home
+  #         git config --global --add safe.directory /__w/invest/invest
 
-      - name: Install git lfs
-        run: |
-          curl -LO https://github.com/git-lfs/git-lfs/releases/download/v3.6.1/git-lfs-linux-amd64-v3.6.1.tar.gz
-          tar -xvzf git-lfs-linux-amd64-v3.6.1.tar.gz
-          cd git-lfs-3.6.1
-          ./install.sh
+  #         # uninstall InVEST if it was already in the restored cache
+  #         python -m pip uninstall -y natcap.invest
+  #         python -m build --wheel
+  #         ls -la dist
+  #         python -m pip install $(find dist -name "natcap.invest*.whl")
+  #         python -m pip list
 
-      - name: Run model tests
-        run: |
-          python -m pytest -s tests/test_validation.py
+  #     - name: Install git lfs
+  #       run: |
+  #         curl -LO https://github.com/git-lfs/git-lfs/releases/download/v3.6.1/git-lfs-linux-amd64-v3.6.1.tar.gz
+  #         tar -xvzf git-lfs-linux-amd64-v3.6.1.tar.gz
+  #         cd git-lfs-3.6.1
+  #         ./install.sh
 
-      - name: Upload wheel artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: Wheel for ${{ matrix.os }} ${{ matrix.python-version }}
-          path: dist
+  #     - name: Run model tests
+  #       run: |
+  #         python -m pytest -s tests/test_validation.py
 
-      - name: Upload conda env artifact
-        uses: actions/upload-artifact@v4
-        continue-on-error: true
-        with:
-          name: Conda Env for ${{ matrix.os }} ${{ matrix.python-version }}
-          path: conda-env.txt
+  #     - name: Upload wheel artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Wheel for ${{ matrix.os }} ${{ matrix.python-version }}
+  #         path: dist
 
-      - name: Authenticate GCP
-        if: github.event_name != 'pull_request'
-        uses: google-github-actions/auth@v2
-        with:
-          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACC_KEY }}
+  #     - name: Upload conda env artifact
+  #       uses: actions/upload-artifact@v4
+  #       continue-on-error: true
+  #       with:
+  #         name: Conda Env for ${{ matrix.os }} ${{ matrix.python-version }}
+  #         path: conda-env.txt
 
-      - name: Set up GCP
-        if: github.event_name != 'pull_request'
-        uses: google-github-actions/setup-gcloud@v2
+  #     - name: Authenticate GCP
+  #       if: github.event_name != 'pull_request'
+  #       uses: google-github-actions/auth@v2
+  #       with:
+  #         credentials_json: ${{ secrets.GOOGLE_SERVICE_ACC_KEY }}
 
-      - name: Deploy artifacts to GCS
-        if: github.event_name != 'pull_request'
-        run: make deploy
+  #     - name: Set up GCP
+  #       if: github.event_name != 'pull_request'
+  #       uses: google-github-actions/setup-gcloud@v2
+
+  #     - name: Deploy artifacts to GCS
+  #       if: github.event_name != 'pull_request'
+  #       run: make deploy
 
 
   run-model-tests:
     name: Run model tests
     runs-on: ${{ matrix.os }}
+    container: ${{ matrix.container }}
     needs: check-syntax-errors
     strategy:
       fail-fast: false
       matrix:
         python-version: [3.9, "3.10", "3.11", "3.12", "3.13"]
         os: [windows-latest, macos-13, ubuntu-latest]
+        include:
+          - os: ubuntu-latest
+            container: quay.io/pypa/manylinux_2_28_x86_64
     steps:
       - uses: actions/checkout@v4
         with:
